remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Combinatorics and Geometry in İstanbul
description: "August 5-6, 2025 | Bahçeşehir University"

markdown: kramdown
kramdown:
  math_engine: mathjax
